#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import os
import sys

if len(sys.argv) != 4:
  print "Usage: $ generate template/template.html contentDir outputDir"
  exit()

else:
    try:
        srcDir = os.path.abspath(sys.argv[2])
        srcFiles = os.listdir(srcDir)
        targetDir = os.path.abspath(sys.argv[3])
        template = open(sys.argv[1], "r")

        for srcFile in srcFiles:
            if os.path.splitext(srcFile)[1] == ".html":
                content = open(os.path.join(srcDir,srcFile), "r")
                output = open(os.path.join(targetDir,srcFile),"w")

                template.seek(0)

                for t in template:
                    if t.rstrip() == "{.}":
                        for c in content:
                            output.write( c )
                    else:
                        output.write( t )
            
                output.close()
                content.close()
        
    except:
        print "Ooops!"
        exit()

template.close()
