#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import sys

if len(sys.argv) != 4:
    print "Usage: $ wrap template.html content.html output.html"
    exit()

try:
    template = open(sys.argv[1], "r")
    content = open(sys.argv[2], "r")
    output = open(sys.argv[3], "w")

    for t in template:
        if t.rstrip() == "{.}":
            for c in content:
                output.write( c )
        else:
            output.write( t )
except:
    print "Ooops!"
    exit()

template.close()
content.close()
output.close()
