#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

set -e
log=`pwd`/qpidd.log
# Start the daemon, recording its PID.
../src/qpidd > $log 2>&1 & pid=$!

# Arrange to kill the daemon upon any type of termination.
trap 'status=$?; kill $pid; exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

# Run C++ client tests.
run_test() {
    test="$*"
    echo -n "Running: $test ... "
    if $test >test.out 2>&1 ; then
	echo " Passed" ;
    else
	echo " FAILED. Output:";
	cat test.out
	FAILED=yes
    fi
    rm -f test.out
}

run_test ./client_test
run_test ./topictest -l2 -m2 -b1

# Run the python tests.
if test -d ../../python ;  then
    cd ../../python && ./run-tests -v -I cpp_failing.txt
else
    echo Warning: python tests not found.
fi

# TODO aconway 2006-12-13: run the other client tests.

rm -f $log
