#!/bin/sh

# Check AIS requirements tests if found.
id -nG | grep '\<ais\>' >/dev/null || \
    NOGROUP="You are not a member of the ais group."
ps -u root | grep aisexec >/dev/null || \
    NOAISEXEC="The aisexec daemon is not running as root"

if test -n "$NOGROUP" -o -n "$NOAISEXEC"; then
    cat <<EOF

    =========== WARNING: NOT RUNNING AIS TESTS ==============

    Tests that depend on the openais library (used for clustering)
    will not be run because:

    $NOGROUP
    $NOAISEXEC

    ==========================================================
    
EOF
    exit 0;			# A warning, not a failure.
fi

# Run the tests
srcdir=`dirname $0`
$srcdir/start_cluster 4
./ais_test
ret=$?
$srcdir/stop_cluster 
exit $ret

