#!/bin/sh
# A simple manual failover test, sends a stream of numbered messages.
# You can kill the connected broker and verify that the clients reconnect 
# and no messages are lost.

URL=$1
test -n "$URL" || { echo Usage: $0 URL ; exit 1; }
SEND=$(mktemp /tmp/send.XXXXXXXXXX)
RECV=$(mktemp /tmp/recv.XXXXXXXXXX)
echo $SEND $RECV

seq 1000000 > $SEND

qpid-send -a 'cluster_failover;{create:always}' -b $URL --connection-options "{reconnect:true}" --send-rate 10 --content-stdin < $SEND &

while msg=$(qpid-receive -m1 -f -a 'cluster_failover;{create:always}' -b $URL --connection-options "{reconnect:true,heartbeat:1}"); do
    echo -n $msg; date
done
wait
