#!/bin/sh
# Without arguments run all daemon tests, exit status is number of failures.
# With arguments run just the test named by $1.
#

TEMP=`mktemp`
qpidd="../qpidd --log.output qpidd.log"
client_tests=./client_test
trap 'rm -f $TEMP' 0

fail() { echo FAIL: $0:$* 1>&2; exit 1; }

# Start and stop daemon on default port.
PID=`$qpidd --check` && fail $LINENO: qpidd already running pid=$PID
$qpidd -d || fail $LINENO: $qpidd -d failed
$qpidd -c >/dev/null || fail $LINENO: qpidd --check says qpidd did not start
./client_test > $TEMP || fail $LINENO:  client_test: `cat $TEMP`
$qpidd -q || fail $LINENO: qpidd -q failed
$qpidd -c >/dev/null && fail $LINENO: Still running after quit.

# Start and stop daemon on dynamic port.
export QPID_PORT=`$qpidd -dp0`
# Note: QPID_PORT fom environment will be used below here:
$qpidd -c >/dev/null || fail $LINENO: qpidd did not start. QPID_PORT=$QPID_PORT
$qpidd -q || fail $LINENO: qpidd -q failed. QPID_PORT=$QPID_PORT
$qpidd -c >/dev/null && fail $LINENO: Still running after start. QPID_PORT=$QPID_PORT

# FIXME aconway 2007-06-11: run client test, needs a --port option.


true
