#!/bin/sh
# Run the python tests.

QPID_PORT=${QPID_PORT:-5672}
PYTHON_TESTS=${PYTHON_TESTS:-$*}
MY_DIR=$(dirname $(which $0))
QPID_PYTHON_DIR=${QPID_PYTHON_DIR:-$MY_DIR/../../../python}

do_tests() {
    SPEC=$1
    FAILING=$2
    ./run-tests --skip-self-test -v -s $SPEC -I $FAILING -b localhost:$QPID_PORT $PYTHON_TESTS || { echo "FAIL python tests for $SPEC"; exit 1; }
}

cd ${QPID_PYTHON_DIR} || { echo "Cannot cd ${QPID_PYTHON_DIR}"; exit 1; }
do_tests 0-10-errata cpp_failing_0-10.txt

