#!/bin/sh

# Check AIS requirements and run tests if found.
id -ng | grep '\<ais\>' >/dev/null || \
    NOGROUP="The ais group is not your primary group."
ps -u root | grep aisexec >/dev/null || \
    NOAISEXEC="The aisexec daemon is not running as root"

if test -n "$NOGROUP" -o -n "$NOAISEXEC"; then
    cat <<EOF

    =========== WARNING: NOT RUNNING AIS TESTS ==============

    Tests that depend on the openais library (used for clustering)
    will not be run because:

    $NOGROUP
    $NOAISEXEC

    ==========================================================
    
EOF
    exit 0;                     # A warning, not a failure.
fi


host=127.0.0.1

src_root=..
module_dir=$src_root/.libs
n_messages=300000
report_frequency=10000
verbosity=1


exec `dirname $0`/failover_soak $src_root $module_dir $host ./declare_queues ./replaying_sender ./resuming_receiver $n_messages $report_frequency $verbosity

