#!/bin/sh
# Run the federation tests.
MY_DIR=`dirname \`which $0\``
PYTHON_DIR=${MY_DIR}/../../../python

trap stop_brokers INT TERM QUIT

start_brokers() {
    ../qpidd --daemon --port 0 --no-data-dir --no-module-dir --auth no > qpidd.port
    LOCAL_PORT=`cat qpidd.port`
    ../qpidd --daemon --port 0 --no-data-dir --no-module-dir --auth no > qpidd.port
    REMOTE_PORT=`cat qpidd.port`
}

stop_brokers() {
        ../qpidd -q --port $LOCAL_PORT
        ../qpidd -q --port $REMOTE_PORT
}

if test -d ${PYTHON_DIR} ;  then
    start_brokers
    echo "Running federation tests using brokers on ports $LOCAL_PORT $REMOTE_PORT"
    PYTHONPATH=${PYTHON_DIR}
    export PYTHONPATH
    ${MY_DIR}/federation.py -v -s ${MY_DIR}/../../../specs/amqp.0-10-qpid-errata.xml -b localhost:$LOCAL_PORT --remote-port $REMOTE_PORT $@
    RETCODE=$?
    stop_brokers
    if test x$RETCODE != x0; then 
        echo "FAIL federation tests"; exit 1;
    fi
fi

