#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

srcdir=$(dirname $0)
. $srcdir/test_env.sh checkout $srcdir/../../.. ../.. || exit 1
. $srcdir/ais_check

TEST_EXEC=$QPID_PYTHON_COMMANDS/qpid-python-test
test -x  $TEST_EXEC || { echo Skipping test, $TEST_EXEC not found; exit 0; }

PYTHONPATH=$srcdir:$PYTHONPATH

# Delete old cluster test data
OUTDIR=brokertest.tmp
rm -rf $OUTDIR
mkdir -p $OUTDIR

# Ignore tests requiring a store by default. 
CLUSTER_TESTS_IGNORE=${CLUSTER_TESTS_IGNORE:--i cluster_tests.StoreTests.* -I $srcdir/cluster_tests.fail}
CLUSTER_TESTS=${CLUSTER_TESTS:-$*}

set -x
with_ais_group $TEST_EXEC -DOUTDIR=$OUTDIR -m cluster_tests $CLUSTER_TESTS_IGNORE $CLUSTER_TESTS || exit 1
rm -rf $OUTDIR
#exit 0
