#!/bin/sh
# Start a cluster of brokers on local host, put the list of ports for cluster members in cluster.ports
#

# Execute command with the ais group set.
with_ais_group() {
    id -nG | grep '\<ais\>' >/dev/null || { echo "You are not a member of the ais group." 1>&2; exit 1; }
    echo $* | newgrp ais
}

test -f cluster.ports && { echo "cluster.ports file already exists" ; exit 1; }
rm -f cluster*.log
SIZE=$1; shift
CLUSTER=`pwd`		# Cluster name=pwd, avoid clashes.
OPTS="-d --load-module ../.libs/cluster.so  --cluster-name=$CLUSTER --no-data-dir --auth=no $*"

if test "$SIZE" = "one"; then	# Special case of singleton cluster, use default port.
    ../qpidd -q
    with_ais_group ../qpidd $OPTS --log-to-file=cluster.log || exit 1
else
    for (( i=0; i<SIZE; ++i )); do
	PORT=`with_ais_group ../qpidd  -p0 --log-to-file=cluster$i.log $OPTS`  || exit 1
	echo $PORT >> cluster.ports
    done
fi

