#!/bin/sh
# Start a cluster of brokers on local host.
# Print the cluster's URL.
#

test -f cluster.ports && { echo "cluster.ports file already exists" ; exit 1; }
test -z "$*" && { echo "Usage: $0 cluster-size [options]"; exit 1; }

SIZE=$1
shift
OPTS=$*

for (( i=0; i<SIZE; ++i )); do
    PORT=`../qpidd -dp0 --log.output=broker$i.log $OPTS` || exit 1
    PORTS="$PORT $PORTS"
done
echo $PORTS > cluster.ports
    
 
