#!/bin/sh
# Start a cluster of brokers on local host, put the list of ports for cluster members in cluster.ports
#
echo $1 | grep '^[0-9][0-9]*$' > /dev/null || { echo "Usage: $0 cluster-size [options]"; exit 1; }

# Execute command with the ais group set.
with_ais_group() {
    id -nG | grep '\<ais\>' >/dev/null || { echo "You are not a member of the ais group."; exit 1; }
    echo $* | newgrp ais
}

test -f cluster.ports && { echo "cluster.ports file already exists" ; exit 1; }
rm -f cluster*.log
SIZE=$1; shift
CLUSTER=`pwd`		# Cluster name=pwd, avoid clashes.

for (( i=0; i<SIZE; ++i )); do
    OPTS="--load-module ../.libs/libqpidcluster.so -dp0 --log-output=cluster$i.log --cluster-name=$CLUSTER --no-data-dir --auth=no $*"
    PORT=`with_ais_group ../qpidd $OPTS`  || exit 1
    echo $PORT >> cluster.ports
done

 
