#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Without arguments run all daemon tests, exit status is number of failures.
# With arguments run just the test named by $1.
#

TEMP=`mktemp`
trap 'rm -f $TEMP' 0
qpidd=../src/qpidd
client_test=./client_test

fail() { echo FAIL: $0:$* 1>&2; exit 1; }

# Start and stop daemon.
PID=`$qpidd --check>/dev/null 2>&1` && fail $LINENO: qpidd already running $PID
$qpidd -d || $LINENO: qpidd -d failed
$qpidd --check >/dev/null || fail $LINENO: qpidd --check says qpidd didnt start
$client_test > $TEMP || fail $LINENO:  client_test: `cat $TEMP`
$qpidd -q || fail $LINENO: qpidd -q failed
true
