#!/bin/sh

set -e
log=`pwd`/qpidd.log
# Start the daemon, recording its PID.
../src/qpidd > $log 2>&1 & pid=$!

# Arrange to kill the daemon upon any type of termination.
trap 'status=$?; kill $pid; exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

# Run the tests.
cd ../../python && ./run-tests -v -I cpp_failing.txt

rm -f $log
