#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

test -x $abs_srcdir/../../python/run-tests || {
    echo WARNING: Python tests not available, skipping.
    exit 0;
}

if test "$VERBOSE" = yes; then
  set -x
  qpidd --version
fi

. $srcdir/setup

fail=0
pid=0

# Start the daemon, recording its PID.
$vg $abs_builddir/../src/qpidd > log 2>&1 & pid=$!

# FIXME: remove this sleep kludge once qpidd provides a way
sleep 4

# Run the tests.
( cd $abs_srcdir/../../python \
    && python ./run-tests -v -I cpp_failing.txt -s ../specs/amqp.0-9.no-wip.xml ) || fail=1 

kill $pid || { echo FAIL: process already died; cat log; fail=1; }

wait $pid
# FIXME: when we have a way to make qpidd shutdown gracefully
# (i.e. with expected exit status of 0), replace the above with this:
# wait $pid || fail=1

vg_check log || fail=1

# Tell the exit trap not to kill any process.
pid=0

(exit $fail); exit $fail
