#!/bin/sh

set -e
log=`pwd`/qpidd.log
# Start the daemon, recording its PID.
../src/qpidd > $log 2>&1 & pid=$!

# Arrange to kill the daemon upon any type of termination.
trap 'status=$?; kill $pid; rm -f test.out; exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

# Run C++ client tests.
run_test() {
    test="$*"
    echo -n "Running: $test ... "
    if $test >test.out 2>&1 ; then
	echo " Passed" ;
    else
	echo " FAILED. Output:";
	cat test.out
	FAILED=yes
    fi
    rm -f test.out
}

run_test ./client_test
run_test `dirname $0`/topictest -s2 -m2 -b1

# FIXME aconway 2007-01-08: Re-enable python tests when the brach
# is functional again.
echo "WARNING: PYTHON TESTS DISABLED TILL BRANCH IS FUNCTIONAL"

# Run the python tests.
# if test -d ../../python ;  then
#     cd ../../python && ./run-tests -v -I cpp_failing.txt
# else
#     echo Warning: python tests not found.
# fi

# TODO aconway 2006-12-13: run the other client tests.

rm -f $log
