#!/bin/bash
# Run the C++ topic test

# Defaults
SUBSCRIBERS=10
MESSAGES=2000
BATCHES=10

while getopts "s:m:b:" opt ; do
    case $opt in
	s) SUBSCRIBERS=$OPTARG ;;
	m) MESSAGES=$OPTARG ;;
	b) BATCHES=$OPTARG ;;
	?)
	    echo "Usage: %0 [-s <subscribers>] [-m <messages.] [-b <batches>]"
	    exit 1
	    ;;
    esac
done

subscribe() {
    ID=$1
    echo "subscriber $ID"
    ./topic_listener > subscriber.$ID 2>&1 || {
	echo "SUBSCRIBER %ID FAILED: " ;
	cat subscriber.$ID
    }
    rm subscriber.$ID
}

publish() {
    ./topic_publisher -messages $MESSAGES -batches $BATCHES -subscribers $SUBSCRIBERS
}

for ((i=$SUBSCRIBERS ; i--; )); do
    subscribe $i &
done
sleep 1
STATS=~/bin/topictest.times
echo "---- topictest `date`" >> $STATS
publish | tee -a $STATS
