#!/usr/bin/env python

import sys, logging
from qpid.connection010 import Connection
from qpid.spec010 import load
from qpid.util import connect
from qpid.datatypes import Message, RangedSet

if "-v" in sys.argv:
  level = logging.DEBUG
else:
  level = logging.WARN

format = "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
logging.basicConfig(level=level, format=format, datefmt='%H:%M:%S')

spec = load("../specs/amqp.0-10.xml")
conn = Connection(connect("0.0.0.0", spec.port), spec)
conn.start(timeout=10)

ssn = conn.session("my-session", timeout=10)

ssn.queue_declare("asdf")


ssn.message_transfer("this", None, None, Message("testing..."))
props = ssn.delivery_properties(routing_key="asdf")
ssn.message_transfer("is", None, None, Message(props, "more testing..."))
ssn.message_transfer("a")
ssn.message_transfer("test")

m1 = ssn.incoming("this").get()
print m1
m2 = ssn.incoming("is").get()
print m2
m3 = ssn.incoming("a").get()
print m3
m4 = ssn.incoming("test").get()
print m4

ssn.message_accept(RangedSet(m1.id, m2.id, m3.id, m4.id))

print ssn.queue_query("testing")

ssn.close(timeout=10)
conn.close(timeout=10)
