#!/usr/bin/env python
from qpid.connection import Connection
from qpid.util import connect
from qpid.datatypes import uuid4, Message

# connect to the server and start a session
conn = Connection(connect("127.0.0.1", 5672))
conn.start()
ssn = conn.session(str(uuid4()))

# create a queue
ssn.queue_declare("test-queue")

# publish a message
dp = ssn.delivery_properties(routing_key="test-queue")
mp = ssn.message_properties(content_type="text/plain")
msg = Message(dp, "Hello World!")
ssn.message_transfer(message=msg)

# subscribe to a queue
ssn.message_subscribe(queue="test-queue", destination="messages")
incoming = ssn.incoming("messages")

# start incoming message flow
incoming.start()

# grab a message from the queue
print incoming.get(timeout=10)

# cancel the subscription and close the session and connection
ssn.message_cancel(destination="messages")
ssn.close()
conn.close()
