/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/*
 * This file is auto-generated by Qpid Gentools v.0.1 - do not modify.
 * Supported AMQP version:
 *   0-91
 */

package org.apache.qpid.framing;

import java.io.DataOutput;
import java.io.IOException;

import org.apache.qpid.AMQException;

public class BasicRecoverSyncOkBody extends AMQMethodBodyImpl implements EncodableAMQDataBlock, AMQMethodBody
{

    public static final int CLASS_ID =  60;
    public final int _ownMethodId;

    // Fields declared in specification

    // Constructor
    public BasicRecoverSyncOkBody(ProtocolVersion protocolVersion)
    {
        if(ProtocolVersion.v0_91.equals(protocolVersion))
        {
            _ownMethodId = 111;
        }
        else
        {
            _ownMethodId = 101;
        }
    }


    public int getClazz()
    {
        return CLASS_ID;
    }

    public int getMethod()
    {
        return _ownMethodId;
    }


    protected int getBodySize()
    {
        return 0;
    }

    public void writeMethodPayload(DataOutput buffer) throws IOException
    {
    }

    public boolean execute(MethodDispatcher dispatcher, int channelId) throws AMQException
	{
        return dispatcher.dispatchBasicRecoverSyncOk(this, channelId);
	}

    public String toString()
    {
         return "[BasicRecoverSyncOkBody]";
    }

}
