#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

if test -z ${QPID_DIR} ; then
    cat <<EOF

	===========  WARNING: PYTHON TESTS DISABLED ==============

	QPID_DIR not set.

	===========================================================

EOF
	exit
fi

. `dirname $0`/tests_env.sh

MODULENAME=python_tests

echo "Running Python tests in module ${MODULENAME}..."

case x$1 in
    xSHORT_TEST)
        DEFAULT_PYTHON_TESTS="*.client_persistence.ExchangeQueueTests.* *.flow_to_disk.SimpleMaxSizeCountTest.test_browse_recover *.flow_to_disk.SimpleMaxSizeCountTest.test_durable_browse_recover *.flow_to_disk.MultiDurableQueueDurableMsgBrowseRecoverTxPTxCTest.test_mixed_limit_2" ;;
    xLONG_TEST)
        DEFAULT_PYTHON_TESTS= ;;
    x)
        DEFAULT_PYTHON_TESTS="*.client_persistence.* *.flow_to_disk.SimpleMaxSizeCountTest.* *.flow_to_disk.MultiDurableQueue*.test_mixed_limit_1 *.flow_to_disk.MultiQueue*.test_mixed_limit_1 *.resize.SimpleTest.* *.federation.*" ;;
    *)
        DEFAULT_PYTHON_TESTS=$1
esac

PYTHON_TESTS=${PYTHON_TESTS:-${DEFAULT_PYTHON_TESTS}}

OUTDIR=${MODULENAME}.tmp
rm -rf $OUTDIR

# To debug a test, add the following options to the end of the following line:
# -v DEBUG -c qpid.messaging.io.ops [*.testName]
${PYTHON_DIR}/qpid-python-test -m ${MODULENAME} -I ${FAILING_PYTHON_TESTS} ${PYTHON_TESTS} -DOUTDIR=$OUTDIR #-v DEBUG
RETCODE=$?

if test x${RETCODE} != x0; then
    exit 1;
fi
exit 0
