#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
set -e
aclocal -I m4
autoheader
libtoolize --automake

# These are needed only if you don't already have the gen/*.{h,cpp} files.
: ${JAVA=java}
: ${JAVAC=javac}
export JAVA JAVAC

# If we're building in the qpid tree, we can generate
# some Makefile snippets:

if test -d ../gentools && test -d ../specs; then
  # Transform gen/Makefile.am, removing automake-constructs and the
  # contents of the sole automake-else clause (the warning), then
  # use the result to run the rules that create gen-src.mk, a file
  # that must be created before we run automake.
  (cd gen && rm -f gen-src.mk
    perl -ne '/warning:|^(if|else|endif|include)\b/ or print' Makefile.am \
	| make -f - srcdir=. gen-src.mk > /dev/null )
fi

# Generate (for automake) lots of repetitive parts of tests/Makefile.am.
(cd tests && rm -f gen.mk
  perl -ne '/^include / or print' Makefile.am \
      | make -f - abs_srcdir=`dirname $(pwd)` gen.mk > /dev/null )

automake
autoconf

if [ "$1" = "-build" -o "$1" = "--build" ] ; then
    ./configure
    make
    make check
fi
