#!/bin/sh
set -e
aclocal -I m4
autoheader
libtoolize --automake

# Generate (for automake) lots of repetitive parts of tests/Makefile.am.
(cd tests && rm -f gen.mk
  perl -ne '/^include / or print' Makefile.am \
      | make -f - abs_srcdir=`dirname $(pwd)` gen.mk )

automake
autoconf
