#!/bin/sh
# Verify all C++/python example combinations.
#

src=$1 ; build=$2

verify=$src/../bin/verify
qpidd=$build/src/qpidd
cpp=$build/examples/examples
python=$src/../python
 
trap "$qpidd -q" exit
export QPID_PORT=`$qpidd -dp0 --data-dir ""`
export PYTHON_EXAMPLES=$python/examples
export PYTHONPATH=$python:$PYTHONPATH
export AMQP_SPEC=$src/../specs/amqp.0-10-preview.xml

find="find $cpp"
test -d $PYTHON_EXAMPLES && find="$find $PYTHON_EXAMPLES"
find="$find -name verify"
test -d $PYTHON_EXAMPLES && \
    find="$find -o -name verify_cpp_python -o -name verify_python_cpp"
$verify `$find`

