client_test_SOURCES = client_test.cpp
client_test_LDADD = $(lib_client) $(lib_common) $(extra_libs)
echo_service_SOURCES = echo_service.cpp
echo_service_LDADD = $(lib_client) $(lib_common) $(extra_libs)
topic_listener_SOURCES = topic_listener.cpp
topic_listener_LDADD = $(lib_client) $(lib_common) $(extra_libs)
topic_publisher_SOURCES = topic_publisher.cpp
topic_publisher_LDADD = $(lib_client) $(lib_common) $(extra_libs)
AccumulatedAckTest_la_SOURCES = AccumulatedAckTest.cpp
AccumulatedAckTest_la_LIBADD = $(lib_common)
AccumulatedAckTest_la_LIBADD += $(lib_broker) $(extra_libs)
AccumulatedAckTest_la_LDFLAGS = -module -rpath $(abs_builddir)
ChannelTest_la_SOURCES = ChannelTest.cpp
ChannelTest_la_LIBADD = $(lib_common)
ChannelTest_la_LIBADD += $(lib_broker) $(extra_libs)
ChannelTest_la_LDFLAGS = -module -rpath $(abs_builddir)
ConfigurationTest_la_SOURCES = ConfigurationTest.cpp
ConfigurationTest_la_LIBADD = $(lib_common)
ConfigurationTest_la_LIBADD += $(lib_broker) $(extra_libs)
ConfigurationTest_la_LDFLAGS = -module -rpath $(abs_builddir)
ExchangeTest_la_SOURCES = ExchangeTest.cpp
ExchangeTest_la_LIBADD = $(lib_common)
ExchangeTest_la_LIBADD += $(lib_broker) $(extra_libs)
ExchangeTest_la_LDFLAGS = -module -rpath $(abs_builddir)
HeadersExchangeTest_la_SOURCES = HeadersExchangeTest.cpp
HeadersExchangeTest_la_LIBADD = $(lib_common)
HeadersExchangeTest_la_LIBADD += $(lib_broker) $(extra_libs)
HeadersExchangeTest_la_LDFLAGS = -module -rpath $(abs_builddir)
InMemoryContentTest_la_SOURCES = InMemoryContentTest.cpp
InMemoryContentTest_la_LIBADD = $(lib_common)
InMemoryContentTest_la_LIBADD += $(lib_broker) $(extra_libs)
InMemoryContentTest_la_LDFLAGS = -module -rpath $(abs_builddir)
LazyLoadedContentTest_la_SOURCES = LazyLoadedContentTest.cpp
LazyLoadedContentTest_la_LIBADD = $(lib_common)
LazyLoadedContentTest_la_LIBADD += $(lib_broker) $(extra_libs)
LazyLoadedContentTest_la_LDFLAGS = -module -rpath $(abs_builddir)
MessageBuilderTest_la_SOURCES = MessageBuilderTest.cpp
MessageBuilderTest_la_LIBADD = $(lib_common)
MessageBuilderTest_la_LIBADD += $(lib_broker) $(extra_libs)
MessageBuilderTest_la_LDFLAGS = -module -rpath $(abs_builddir)
MessageTest_la_SOURCES = MessageTest.cpp
MessageTest_la_LIBADD = $(lib_common)
MessageTest_la_LIBADD += $(lib_broker) $(extra_libs)
MessageTest_la_LDFLAGS = -module -rpath $(abs_builddir)
QueueRegistryTest_la_SOURCES = QueueRegistryTest.cpp
QueueRegistryTest_la_LIBADD = $(lib_common)
QueueRegistryTest_la_LIBADD += $(lib_broker) $(extra_libs)
QueueRegistryTest_la_LDFLAGS = -module -rpath $(abs_builddir)
QueueTest_la_SOURCES = QueueTest.cpp
QueueTest_la_LIBADD = $(lib_common)
QueueTest_la_LIBADD += $(lib_broker) $(extra_libs)
QueueTest_la_LDFLAGS = -module -rpath $(abs_builddir)
TopicExchangeTest_la_SOURCES = TopicExchangeTest.cpp
TopicExchangeTest_la_LIBADD = $(lib_common)
TopicExchangeTest_la_LIBADD += $(lib_broker) $(extra_libs)
TopicExchangeTest_la_LDFLAGS = -module -rpath $(abs_builddir)
TxAckTest_la_SOURCES = TxAckTest.cpp
TxAckTest_la_LIBADD = $(lib_common)
TxAckTest_la_LIBADD += $(lib_broker) $(extra_libs)
TxAckTest_la_LDFLAGS = -module -rpath $(abs_builddir)
TxBufferTest_la_SOURCES = TxBufferTest.cpp
TxBufferTest_la_LIBADD = $(lib_common)
TxBufferTest_la_LIBADD += $(lib_broker) $(extra_libs)
TxBufferTest_la_LDFLAGS = -module -rpath $(abs_builddir)
TxPublishTest_la_SOURCES = TxPublishTest.cpp
TxPublishTest_la_LIBADD = $(lib_common)
TxPublishTest_la_LIBADD += $(lib_broker) $(extra_libs)
TxPublishTest_la_LDFLAGS = -module -rpath $(abs_builddir)
ValueTest_la_SOURCES = ValueTest.cpp
ValueTest_la_LIBADD = $(lib_common)
ValueTest_la_LIBADD += $(lib_broker) $(extra_libs)
ValueTest_la_LDFLAGS = -module -rpath $(abs_builddir)
BodyHandlerTest_la_SOURCES = BodyHandlerTest.cpp
BodyHandlerTest_la_LIBADD = $(lib_common)
BodyHandlerTest_la_LIBADD += $(lib_broker) $(extra_libs)
BodyHandlerTest_la_LDFLAGS = -module -rpath $(abs_builddir)
FieldTableTest_la_SOURCES = FieldTableTest.cpp
FieldTableTest_la_LIBADD = $(lib_common)
FieldTableTest_la_LIBADD += $(lib_broker) $(extra_libs)
FieldTableTest_la_LDFLAGS = -module -rpath $(abs_builddir)
FramingTest_la_SOURCES = FramingTest.cpp
FramingTest_la_LIBADD = $(lib_common)
FramingTest_la_LIBADD += $(lib_broker) $(extra_libs)
FramingTest_la_LDFLAGS = -module -rpath $(abs_builddir)
HeaderTest_la_SOURCES = HeaderTest.cpp
HeaderTest_la_LIBADD = $(lib_common)
HeaderTest_la_LIBADD += $(lib_broker) $(extra_libs)
HeaderTest_la_LDFLAGS = -module -rpath $(abs_builddir)
ExceptionTest_la_SOURCES = ExceptionTest.cpp
ExceptionTest_la_LIBADD = $(lib_common)
ExceptionTest_la_LIBADD += $(lib_broker) $(extra_libs)
ExceptionTest_la_LDFLAGS = -module -rpath $(abs_builddir)
EventChannelTest_la_SOURCES = EventChannelTest.cpp
EventChannelTest_la_LIBADD = $(lib_common)
EventChannelTest_la_LIBADD += $(lib_broker) $(extra_libs)
EventChannelTest_la_LDFLAGS = -module -rpath $(abs_builddir)
EventChannelThreadsTest_la_SOURCES = EventChannelThreadsTest.cpp
EventChannelThreadsTest_la_LIBADD = $(lib_common)
EventChannelThreadsTest_la_LIBADD += $(lib_broker) $(extra_libs)
EventChannelThreadsTest_la_LDFLAGS = -module -rpath $(abs_builddir)
check_LTLIBRARIES = AccumulatedAckTest.la ChannelTest.la ConfigurationTest.la ExchangeTest.la HeadersExchangeTest.la InMemoryContentTest.la LazyLoadedContentTest.la MessageBuilderTest.la MessageTest.la QueueRegistryTest.la QueueTest.la TopicExchangeTest.la TxAckTest.la TxBufferTest.la TxPublishTest.la ValueTest.la BodyHandlerTest.la FieldTableTest.la FramingTest.la HeaderTest.la ExceptionTest.la EventChannelTest.la EventChannelThreadsTest.la
