#!/bin/bash

if test "$VERBOSE" = yes; then
  set -x
  qpidd --version
fi

. $srcdir/setup

fail=0
pid=0

# Start the daemon, recording its PID.
$vg $abs_builddir/../src/qpidd > log 2>&1 & pid=$!

# FIXME: remove this sleep kludge once qpidd provides a way
sleep 4

# Run the tests.
( cd $abs_srcdir/../../python \
    && python ./run-tests -v -I cpp_failing.txt ) || fail=1 

kill $pid || { echo FAIL: process already died; cat log; fail=1; }

wait $pid
# FIXME: when we have a way to make qpidd shutdown gracefully
# (i.e. with expected exit status of 0), replace the above with this:
# wait $pid || fail=1

vg_check log || fail=1

# Tell the exit trap not to kill any process.
pid=0

(exit $fail); exit $fail
