#!/bin/bash

Usage() 
{
  echo "usage: $0 1.1|2.0 release-number (e.g. 2.0.1)"
  exit 2
}

if [[ $# -ne 2 ]]; then
  Usage
fi

dotNetVersion=$1
releaseName=Qpid.NET-$2-FX$dotNetVersion

if [[ $dotNetVersion == "1.1" ]]; then
  binDir=Qpid.Client.Tests/bin/FX1_1/Release
elif [[ $dotNetVersion == "2.0" ]]; then
  binDir=Qpid.Client.Tests/bin/Release
else
  Usage
fi

filesToRelease="
  Qpid.Buffer.dll
  Qpid.Client.Transport.Socket.Blocking.dll
  Qpid.Client.dll
  Qpid.Codec.dll
  Qpid.Common.dll
  Qpid.Messaging.dll
  log4net.dll
  log4net.xml"

releaseDir=build/$releaseName
mkdir -p $releaseDir

for file in $filesToRelease; do
  cp $binDir/$file $releaseDir
done

cd build
jar -cvMf $releaseName.zip $releaseName
