CXX=g++
CXXFLAGS= 
LDFLAGS=-lqpidclient

PROGRAMS=direct_config_queues direct_persistent_config_queues direct_persistent_publisher direct_publisher listener

all: $(PROGRAMS)

clean:
	rm -f $(PROGRAMS) 
