#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Utility to print out currently installed versions of qpid developer
# dependencies. Assumes that some dependencies are installed with RPM.
# 

for p in pkg-config doxygen help2man autoconf automake libtool ; do
    echo `which $p` `$p --version | head -n1`
done

for r in apr boost boost-devel cppunit cppunit-devel graphviz; do
    rpm -q $r
done
