#!/bin/sh
set -e
aclocal -I m4
autoheader
libtoolize --automake

# These are needed only if you don't already have the gen/*.{h,cpp} files.
: ${JAVA=java}
: ${JAVAC=javac}
export JAVA JAVAC

# Generate (for automake) lots of repetitive parts of tests/Makefile.am.
(cd src/tests && rm -f gen.mk
  perl -ne '/^(include |if |else|endif)/ or print' Makefile.am \
      | make -f - abs_srcdir=`dirname $(pwd)` gen.mk > /dev/null )

# Create initial Makefile fragments that will force make to generate
# the real ones.
cat > src/rubygen.mk <<EOF
\$(srcdir)/rubygen.mk: force
	\$(rgen_cmd)
EOF

touch src/generate.mk 

automake
autoconf

if [ "$1" = "-build" -o "$1" = "--build" ] ; then
    shift
    ./configure "$@"
    make
    make check
fi
