#!/bin/sh
set -e
aclocal -I m4
autoheader
libtoolize --automake

# If we're building in the qpid tree, we can generate
# some Makefile snippets:

if test -d ../gentools && test -d ../specs; then
  (cd gen && rm -f gen-src.mk
    perl -ne '/^(abs_srcdir|if|else|endif|include)\b/ or print' Makefile.am \
	| make -f - abs_srcdir=`pwd` srcdir=. gen-src.mk > /dev/null )
fi

# Generate (for automake) lots of repetitive parts of tests/Makefile.am.
(cd tests && rm -f gen.mk
  perl -ne '/^include / or print' Makefile.am \
      | make -f - abs_srcdir=`dirname $(pwd)` gen.mk > /dev/null )

automake
autoconf
