#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

JDATA_DIR=jdata
TAR_DIR=rd_test_jrnls

function get_filename
{
    local prefix=$1
    local file_num=$2
    local suffix=$3
    
    if (( file_num < 10 )); then
        local num="000${file_num}"
    elif (( file_num < 100 )); then
        local num="00${file_num}"
    elif (( file_num < 1000 )); then
        local num="0${file_num}"
    else
        local num="${file_num}"
    fi
    FILENAME=${prefix}${num}${suffix}
    return 0
}

if (( $# != 1 )); then
    echo "Incorrect args, expected 1 arg (usage: \"prep <testnum>\")"
    exit
fi

get_filename "t" $1 ".tar.gz"
if [[ -d ${JDATA_DIR} ]]; then
    rm -rf ${JDATA_DIR}/*
else
    mkdir -p ${JDATA_DIR}
fi
if [[ -f "${TAR_DIR}/${FILENAME}" ]]; then
    tar -C ${JDATA_DIR} -xzf "${TAR_DIR}/${FILENAME}"
else
    echo "Error: file \"${TAR_DIR}/${FILENAME}\" not found."
fi
