#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Do 3 runs of topictests for C++ and Java brokers with reduced output.

. `dirname $0`/env

# Run a short topictest to warm up the broker and iron out startup effects.
flush() {
    topic_listener >/dev/null 2>&1 &
    topic_publisher >/dev/null 2>&1 
}

echo Java broker
broker j ; flush
topictest c | tail -n1
topictest c | tail -n1
topictest c | tail -n1

echo C++ broker
broker c ; flush
topictest c | tail -n1
topictest c | tail -n1
topictest c | tail -n1

# Don't bother with java clients we know they're slower.

