#!/bin/sh

# Check AIS requirements tests if found.
id -nG | grep '\<ais\>' >/dev/null || \
    NOGROUP="You are not a member of the ais group."
ps -u root | grep aisexec >/dev/null || \
    NOAISEXEC="The aisexec daemon is not running as root"

if test -n "$NOGROUP" -o -n "$NOAISEXEC"; then
    cat <<EOF

    =========== WARNING: NOT RUNNING AIS TESTS ==============

    Tests that depend on the openais library (used for clustering)
    will not be run because:

    $NOGROUP
    $NOAISEXEC

    ==========================================================
    
EOF
    exit 0;			# A warning, not a failure.
fi

# Execute command with the ais group set.
with_ais_group() {
    id -nG | grep '\<ais\>' >/dev/null || { echo "You are not a member of the ais group."; exit 1; }
    echo $* | newgrp ais
}

# Run the tests
srcdir=`dirname $0`
with_ais_group ./cluster_test || ERROR=1
exit $ERROR

