#!/bin/sh
# Check for requirements, run AIS tests if found.
#

id -nG | grep '\<ais\>' || \
    NOGROUP="You are not a member of the ais group."
ps -u root | grep aisexec >/dev/null || \
    NOAISEXEC="The aisexec daemon is not running as root"

if test -n "$NOGROUP" -o -n "$NOAISEXEC"; then
    cat <<EOF

    =========== WARNING: NOT RUNNING AIS TESTS ==============

    Tests that depend on the openais library (used for clustering)
    will not be run because:

    $NOGROUP
    $NOAISEXEC

    ==========================================================
    
EOF
    exit 0;			# A warning, not a failure.
fi

echo ./ais_run | newgrp ais
