#!/bin/sh
# Run the python tests.
QPID_PORT=${QPID_PORT:-5672}
PYTHON_TESTS=${PYTHON_TESTS:-$*}
MY_DIR=$(dirname $(which $0))
PYTHON_DIR=${MY_DIR}/../../../python

run() {
    SPEC=$1
    FAILING=$2
    ./run-tests --skip-self-test -v -s $SPEC -I $FAILING -b localhost:$QPID_PORT $PYTHON_TESTS || { echo "FAIL python tests for $SPEC"; exit 1; }
}

if test -d ${PYTHON_DIR} ;  then
    cd ${PYTHON_DIR}
    run 0-10-errata cpp_failing_0-10.txt
else
    echo Warning: python tests not found.
fi
