#!/bin/sh
# Re-start a cluster on the local host.

srcdir=`dirname $0`
$srcdir/stop_cluster
exec $srcdir/start_cluster "$@"
#!/bin/sh
# Re-start a cluster on the local host.

srcdir=`dirname $0`
$srcdir/stop_cluster
exec $srcdir/start_cluster "$@"
#!/bin/sh
# Re-start a cluster on the local host.

srcdir=`dirname $0`
$srcdir/stop_cluster
exec $srcdir/start_cluster "$@"
