#!/bin/sh
# Simple test of encode/decode of a double in application headers
# TODO: this should be expanded to cover a wider set of types and go
# in both directions

srcdir=`dirname $0`
PYTHON_DIR=$srcdir/../../../python
test -f qpidd.port && QPID_PORT=`cat qpidd.port`

./header_test -p $QPID_PORT
export PYTHONPATH=$PYTHON_DIR:$PYTHONPATH
$srcdir/header_test.py "localhost" $QPID_PORT

