#!/usr/bin/env python

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Run the cli-utility tests

from common import *

cli_dir = join(SOURCE_DIR, "management", "python", "bin")

xquery = """
let $w := ./weather
return $w/station = 'Raleigh-Durham International Airport (KRDU)'
   and $w/temperature_f > 50
   and $w/temperature_f - $w/dewpoint > 5
   and $w/wind_speed_mph > 7
   and $w/wind_speed_mph < 20
"""
xquery_file = write(join(WORK_DIR, "xquery_file"), xquery)

# If the xml lib is present, use it.  if not, disable any tests which
# look like they're xml related.
#
# If we start supporting xml on windows, it will need something
# similar here.

if XML_LIB is not None:
    broker_args = "--load-module {0}".format(XML_LIB)
    test_args = ""
else:
    notice("Ignoring XML tests")

    broker_args = ""
    test_args = "--ignore=*xml*"

local_port = start_broker("local", broker_args)
remote_port = start_broker("remote", broker_args)

run_broker_tests(local_port,
                 "-m cli_tests",
                 "-Dremote-port={0}".format(remote_port),
                 "-Dcli-dir={0}".format(cli_dir),
                 "-Dxquery-file={0}".format(xquery_file),
                 test_args)

check_results()
