#!/usr/bin/env python

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from common import *

python_swig_module = join(BUILD_DIR, "bindings", "qpid", "python", "qpid_messaging.py")

if exists(python_swig_module):
    port = start_broker("broker", "--load-module {0}".format(AMQP_LIB))

    ENV["QPID_INTEROP_URL"] = "localhost:{0}".format(port)

    call("qpid-python-test -m interop_tests -DOUTDIR={0}", WORK_DIR)
else:
    warn("Skipping tests: 1.0 messaging client not found")

check_results()
