#!/usr/bin/env python

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from common import *

# ENV["QPID_USE_SWIG_CLIENT"] = "1" # XXX is this necessary?

# XXX These tests hang, and I can't figure out why
# -i *tx_block_threads 

# ENV["QPID_NO_MODULE_DIR"] = "1" # Don't accidentally load installed modules
# ENV["QPID_DATA_DIR"] = ""
# ENV["QPID_CONFIG"] = join(BUILD_DIR, "src", "tests", "qpidd-empty.conf")
# ENV["QPID_PORT"] = ""
# ENV["QPID_LOG_TO_FILE"] = join(BUILD_DIR, "src", "tests", "gah.log")

call("qpid-python-test -m ha_tests -DOUTDIR={0}", WORK_DIR)

check_results()
