#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Script to run a sequence of long-running message group tests via
# make

source env.sh

#set port to connect to via env var
test -s qpidd.port && QPID_PORT=`cat qpidd.port`

#trap cleanup INT TERM QUIT

QUEUE_NAME="group-queue"
GROUP_KEY="My-Group-Id"

BROKER_URL="${QPID_BROKER:-localhost}:${QPID_PORT:-5672}"

run_test() {
    $@
}

##set -x

declare -i i=0
declare -a tests
tests=("qpid-config -b $BROKER_URL add queue $QUEUE_NAME --group-header=${GROUP_KEY} --shared-groups"
    "msg_group_test -b $BROKER_URL -a $QUEUE_NAME --group-key $GROUP_KEY --messages 10007 --receivers 3 --senders 5 --group-size 211 --randomize-group-size --capacity 47 --ack-frequency 97"
    "msg_group_test -b $BROKER_URL -a $QUEUE_NAME --group-key $GROUP_KEY --messages 10007 --receivers 3 --senders 5 --group-size 211 --randomize-group-size --capacity 79 --ack-frequency 79"
    "msg_group_test -b $BROKER_URL -a $QUEUE_NAME --group-key $GROUP_KEY --messages 10007 --receivers 3 --senders 5 --group-size 211 --randomize-group-size --capacity 97 --ack-frequency 47"
    "msg_group_test -b $BROKER_URL -a $QUEUE_NAME --group-key $GROUP_KEY --messages 40000  --receivers 0 --senders 5 --group-size 13 --randomize-group-size"
    "msg_group_test -b $BROKER_URL -a $QUEUE_NAME --group-key $GROUP_KEY --messages 200000 --receivers 3 --senders 0 --capacity 23 --ack-frequency 7"
    "qpid-config -b $BROKER_URL del queue $QUEUE_NAME --force")

while [ -n "${tests[i]}" ]; do
    run_test ${tests[i]}
    RETCODE=$?
    if test x$RETCODE != x0; then
        echo "FAILED message group test.  Failed command: \"${tests[i]}\"";
        exit 1;
    fi
    i+=1
done
