#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#script to run a sequence of ring queue tests via make

#setup path to find qpid-config and sender/receiver test progs
source ./test_env.sh

export PATH=$PWD:$srcdir:$PYTHON_COMMANDS:$PATH

#set port to connect to via env var
test -s qpidd.port && QPID_PORT=`cat qpidd.port`

trap cleanup INT TERM QUIT

QUEUE_NAME="group-queue"
GROUP_KEY="My-Group-Id"

BROKER_URL="-a ${QPID_BROKER:-localhost}:${QPID_PORT:-5672}"

setup() {
    qpid-config $BROKER_URL add queue $QUEUE_NAME --argument="qpid.group_header_key=${GROUP_KEY}"
}

cleanup() {
    qpid-config $BROKER_URL del queue $QUEUE_NAME --force
}

run_test() {

    msg_group_test -a $QUEUE_NAME --group-key $GROUP_KEY --capacity 3 --group-size 13 --ack-frequency 7 --messages 103 --receivers 3 --senders 5
    RETCODE=$?
    cleanup

    if test x$RETCODE != x0; then
        echo "FAIL message group tests"; exit 1;
    fi
}

setup
run_test


