#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

absdir() { echo `cd $1; pwd`; }

srcdir=$(absdir $(dirname $0))
top_builddir=$(absdir ../..)

. $srcdir/python_env.sh

# Check AIS requirements
. $srcdir/ais_check

# Check XML exchange requirements
XML_LIB=$srcdir/../.libs/xml.so
if [ -f ${XML_LIB} ]; then
	export XML_LIB
fi


# Set up environment for python tests
export PYTHONPATH=${srcdir}:${PYTHON_DIR}
export QPIDD_EXEC=${top_builddir}/src/qpidd
export CLUSTER_LIB=${top_builddir}/src/.libs/cluster.so
export QPID_CONFIG_EXEC=${srcdir}/../../../python/commands/qpid-config
export QPID_ROUTE_EXEC=${srcdir}/../../../python/commands/qpid-route
export RECEIVER_EXEC=${top_builddir}/src/tests/receiver
export SENDER_EXEC=${top_builddir}/src/tests/sender


# Check for existence of qpid tools (either in svn tree or full install)
# This prevents make dist / make distcheck from failing without python tools being present
if test ! -x ${top_builddir}/../python/commands/qpid-config; then
	path=`which qpid-config`
	if test $?; then
		echo "WARNING: qpid tools not found, skipping test ${CLUSTER_TEST}" 
		exit 0
	fi
fi

# Delete old cluster test data
OUTDIR=brokertest.tmp
rm -rf $OUTDIR
mkdir -p $OUTDIR

# FIXME aconway 2009-11-06: pass OUTDIR to test.

# Run the test
with_ais_group $PYTHON_COMMANDS/qpid-python-test -m cluster_tests
## || exit 1
#rm -rf $OUTDIR
#exit 0
