#!/usr/bin/env python

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from common import *

port = start_broker("broker")

commands = [
    "qpid-config -b {0} add queue group-queue --group-header=My-Group-Id --shared-groups",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 103 --group-size 13 --receivers 2 --senders 3 --capacity 3 --ack-frequency 7 --randomize-group-size --interleave 3",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 103 --group-size 13 --receivers 2 --senders 3 --capacity 7 --ack-frequency 7 --randomize-group-size",
    "qpid-config -b {0} add queue group-queue-two --group-header=My-Group-Id --shared-groups",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 103 --group-size 13 --receivers 2 --senders 3 --capacity 7 --ack-frequency 3 --randomize-group-size",
    "msg_group_test -b {0} -a group-queue-two --group-key My-Group-Id --messages 103 --group-size 13 --receivers 2 --senders 3 --capacity 3 --ack-frequency 7 --randomize-group-size --interleave 5",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 59  --group-size 5  --receivers 2 --senders 3 --capacity 1 --ack-frequency 3 --randomize-group-size",
    "qpid-config -b {0} del queue group-queue-two --force",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 59  --group-size 3  --receivers 2 --senders 3 --capacity 1 --ack-frequency 1 --randomize-group-size",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 211 --group-size 13 --receivers 2 --senders 3 --capacity 47 --ack-frequency 79 --interleave 53",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 10000  --group-size 1 --receivers 0 --senders 1",
    "msg_group_test -b {0} -a group-queue --group-key My-Group-Id --messages 10000  --receivers 5 --senders 0",
    "qpid-config -b {0} del queue group-queue --force",
]

address = "localhost:{0}".format(port)

for command in commands:
    call(command, address)

check_results()
