#!/bin/sh
# Start a cluster of brokers on local host.
# Print the cluster's URL.
#

test -f cluster.ports && { echo "cluster.ports file already exists" ; exit 1; }
test -z "$*" && { echo "Usage: $0 cluster-size [options]"; exit 1; }

rm -f cluster*.log cluster.ports
SIZE=$1
shift
CLUSTER=`whoami`		# Cluster name=user name, avoid clashes.
OPTS="--load-module ../.libs/libqpidcluster.so -dp0 --log-output=cluster$i.log --cluster-name=$CLUSTER --no-data-dir --auth=no $*"

for (( i=0; i<SIZE; ++i )); do
    PORT=`../qpidd $OPTS`  || exit 1
    echo $PORT >> cluster.ports
done
    
 
