#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Check AIS requirements and run tests if found.
id -ng | grep '\<ais\>' >/dev/null || \
    NOGROUP="The ais group is not your primary group."
ps -u root | grep aisexec >/dev/null || \
    NOAISEXEC="The aisexec daemon is not running as root"

if test -n "$NOGROUP" -o -n "$NOAISEXEC"; then
    cat <<EOF

    =========== WARNING: NOT RUNNING AIS TESTS ==============

    Tests that depend on the openais library (used for clustering)
    will not be run because:

    $NOGROUP
    $NOAISEXEC

    ==========================================================
    
EOF
    exit 0;                     # A warning, not a failure.
fi


host=127.0.0.1

src_root=..
module_dir=$src_root/.libs
n_messages=300000
report_frequency=10000
verbosity=1


exec `dirname $0`/failover_soak $src_root $module_dir $host ./declare_queues ./replaying_sender ./resuming_receiver $n_messages $report_frequency $verbosity

